import type { Product, Category } from "@/lib/types"

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Pain Relief",
    nameAr: "مسكنات الألم",
    slug: "pain-relief",
    icon: "💊",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Vitamins & Supplements",
    nameAr: "الفيتامينات والمكملات",
    slug: "vitamins-supplements",
    icon: "🌿",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Cold & Flu",
    nameAr: "البرد والإنفلونزا",
    slug: "cold-flu",
    icon: "🤧",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Digestive Health",
    nameAr: "صحة الجهاز الهضمي",
    slug: "digestive-health",
    icon: "🫃",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "Skin Care",
    nameAr: "العناية بالبشرة",
    slug: "skin-care",
    icon: "✨",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "First Aid",
    nameAr: "الإسعافات الأولية",
    slug: "first-aid",
    icon: "🩹",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: "Baby Care",
    nameAr: "العناية بالأطفال",
    slug: "baby-care",
    icon: "👶",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: "Diabetes Care",
    nameAr: "رعاية مرضى السكري",
    slug: "diabetes-care",
    icon: "💉",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    name: "Heart Health",
    nameAr: "صحة القلب",
    slug: "heart-health",
    icon: "❤️",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    name: "Women's Health",
    nameAr: "صحة المرأة",
    slug: "womens-health",
    icon: "🌸",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Panadol Extra Tablets",
    nameAr: "بانادول اكسترا أقراص",
    slug: "panadol-extra-tablets",
    description: "Fast and effective pain relief with caffeine boost",
    descriptionAr: "تسكين سريع وفعال للألم مع تعزيز الكافيين",
    price: 25.5,
    compareAtPrice: 30.0,
    images: ["/panadol-extra-tablets.jpg"],
    categoryId: 1,
    category: mockCategories[0],
    brand: "Panadol",
    brandAr: "بانادول",
    stock: 150,
    rating: 4.8,
    reviewsCount: 245,
    requiresPrescription: false,
    dosageForm: "Tablets",
    dosageFormAr: "أقراص",
    activeIngredients: "Paracetamol 500mg, Caffeine 65mg",
    activeIngredientsAr: "باراسيتامول 500 ملغ، كافيين 65 ملغ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Brufen Ibuprofen 400mg",
    nameAr: "بروفين ايبوبروفين 400 ملغ",
    slug: "brufen-ibuprofen-400mg",
    description: "Anti-inflammatory pain reliever for headaches and muscle pain",
    descriptionAr: "مسكن للألم ومضاد للالتهابات للصداع وآلام العضلات",
    price: 18.0,
    compareAtPrice: null,
    images: ["/brufen-ibuprofen-tablets.jpg"],
    categoryId: 1,
    category: mockCategories[0],
    brand: "Brufen",
    brandAr: "بروفين",
    stock: 200,
    rating: 4.7,
    reviewsCount: 189,
    requiresPrescription: false,
    dosageForm: "Tablets",
    dosageFormAr: "أقراص",
    activeIngredients: "Ibuprofen 400mg",
    activeIngredientsAr: "ايبوبروفين 400 ملغ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Voltaren Gel 50g",
    nameAr: "فولتارين جل 50 جرام",
    slug: "voltaren-gel-50g",
    description: "Topical gel for joint and muscle pain relief",
    descriptionAr: "جل موضعي لتخفيف آلام المفاصل والعضلات",
    price: 45.0,
    compareAtPrice: 52.0,
    images: ["/voltaren-gel-tube.jpg"],
    categoryId: 1,
    category: mockCategories[0],
    brand: "Voltaren",
    brandAr: "فولتارين",
    stock: 80,
    rating: 4.9,
    reviewsCount: 312,
    requiresPrescription: false,
    dosageForm: "Gel",
    dosageFormAr: "جل",
    activeIngredients: "Diclofenac Sodium 1%",
    activeIngredientsAr: "ديكلوفيناك الصوديوم 1%",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Aspirin 100mg",
    nameAr: "أسبرين 100 ملغ",
    slug: "aspirin-100mg",
    description: "Low-dose aspirin for heart health and blood thinning",
    descriptionAr: "أسبرين بجرعة منخفضة لصحة القلب وتمييع الدم",
    price: 12.5,
    compareAtPrice: null,
    images: ["/aspirin-tablets-box.jpg"],
    categoryId: 9,
    category: mockCategories[8],
    brand: "Bayer",
    brandAr: "باير",
    stock: 300,
    rating: 4.6,
    reviewsCount: 156,
    requiresPrescription: false,
    dosageForm: "Tablets",
    dosageFormAr: "أقراص",
    activeIngredients: "Acetylsalicylic Acid 100mg",
    activeIngredientsAr: "حمض أسيتيل الساليسيليك 100 ملغ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "Centrum Multivitamin",
    nameAr: "سنتروم مالتي فيتامين",
    slug: "centrum-multivitamin",
    description: "Complete daily multivitamin with essential nutrients",
    descriptionAr: "فيتامينات متعددة يومية كاملة مع العناصر الغذائية الأساسية",
    price: 85.0,
    compareAtPrice: 95.0,
    images: ["/centrum-multivitamin-bottle.jpg"],
    categoryId: 2,
    category: mockCategories[1],
    brand: "Centrum",
    brandAr: "سنتروم",
    stock: 120,
    rating: 4.8,
    reviewsCount: 428,
    requiresPrescription: false,
    dosageForm: "Tablets",
    dosageFormAr: "أقراص",
    activeIngredients: "Multivitamins & Minerals",
    activeIngredientsAr: "فيتامينات ومعادن متعددة",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "Vitamin D3 5000 IU",
    nameAr: "فيتامين د3 5000 وحدة",
    slug: "vitamin-d3-5000-iu",
    description: "High-potency vitamin D for bone and immune health",
    descriptionAr: "فيتامين د عالي الفعالية لصحة العظام والمناعة",
    price: 55.0,
    compareAtPrice: null,
    images: ["/vitamin-d3-softgels.jpg"],
    categoryId: 2,
    category: mockCategories[1],
    brand: "Nature Made",
    brandAr: "نيتشر ميد",
    stock: 95,
    rating: 4.7,
    reviewsCount: 267,
    requiresPrescription: false,
    dosageForm: "Softgels",
    dosageFormAr: "كبسولات جيلاتينية",
    activeIngredients: "Cholecalciferol 5000 IU",
    activeIngredientsAr: "كوليكالسيفيرول 5000 وحدة",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Helper functions to simulate database queries
export function getCategories(limit?: number): Category[] {
  return limit ? mockCategories.slice(0, limit) : mockCategories
}

export function getBestsellers(limit?: number): Product[] {
  const sorted = [...mockProducts].sort((a, b) => b.rating - a.rating)
  return limit ? sorted.slice(0, limit) : sorted
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string, limit?: number): Product[] {
  const filtered = mockProducts.filter((p) => p.category.slug === categorySlug)
  return limit ? filtered.slice(0, limit) : filtered
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return mockProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.nameAr.includes(query) ||
      p.brand.toLowerCase().includes(lowerQuery) ||
      p.brandAr.includes(query),
  )
}
