import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  console.log("🌱 Starting database seed...")

  // Clear existing data
  await prisma.productTag.deleteMany()
  await prisma.tag.deleteMany()
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()

  // Create categories
  const categories = await Promise.all([
    prisma.category.create({
      data: {
        name: "Pain Relief",
        nameAr: "مسكنات الألم",
        slug: "pain-relief",
        icon: "💊",
      },
    }),
    prisma.category.create({
      data: {
        name: "Vitamins & Supplements",
        nameAr: "الفيتامينات والمكملات",
        slug: "vitamins-supplements",
        icon: "🌿",
      },
    }),
    prisma.category.create({
      data: {
        name: "Cold & Flu",
        nameAr: "البرد والإنفلونزا",
        slug: "cold-flu",
        icon: "🤧",
      },
    }),
    prisma.category.create({
      data: {
        name: "Digestive Health",
        nameAr: "صحة الجهاز الهضمي",
        slug: "digestive-health",
        icon: "🫁",
      },
    }),
    prisma.category.create({
      data: {
        name: "Skin Care",
        nameAr: "العناية بالبشرة",
        slug: "skin-care",
        icon: "✨",
      },
    }),
    prisma.category.create({
      data: {
        name: "Heart & Blood Pressure",
        nameAr: "القلب وضغط الدم",
        slug: "heart-blood-pressure",
        icon: "❤️",
      },
    }),
    prisma.category.create({
      data: {
        name: "Diabetes Care",
        nameAr: "رعاية مرضى السكري",
        slug: "diabetes-care",
        icon: "🩺",
      },
    }),
    prisma.category.create({
      data: {
        name: "Antibiotics",
        nameAr: "المضادات الحيوية",
        slug: "antibiotics",
        icon: "💉",
      },
    }),
    prisma.category.create({
      data: {
        name: "Baby & Mother Care",
        nameAr: "رعاية الأم والطفل",
        slug: "baby-mother-care",
        icon: "👶",
      },
    }),
    prisma.category.create({
      data: {
        name: "First Aid",
        nameAr: "الإسعافات الأولية",
        slug: "first-aid",
        icon: "🏥",
      },
    }),
  ])

  console.log(`✅ Created ${categories.length} categories`)

  // Create products
  const products = [
    // Pain Relief
    {
      name: "Panadol Extra",
      nameAr: "بانادول اكسترا",
      slug: "panadol-extra",
      brand: "GSK",
      brandAr: "جي إس كي",
      description: "Fast and effective pain relief with paracetamol and caffeine",
      descriptionAr: "تسكين سريع وفعال للألم مع الباراسيتامول والكافيين",
      price: 12.5,
      stock: 150,
      sku: "PAN-EXT-001",
      barCode: "6281007001234",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Paracetamol 500mg + Caffeine 65mg",
      activeIngredientAr: "باراسيتامول 500 ملغ + كافيين 65 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Store below 25°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 25 درجة مئوية",
      warnings: "Do not exceed recommended dose",
      warningsAr: "لا تتجاوز الجرعة الموصى بها",
      categoryId: categories[0].id,
      rating: 4.7,
      reviewsCount: 234,
      images: ["/panadol-extra-tablets.jpg"],
    },
    {
      name: "Brufen 400mg",
      nameAr: "بروفين 400 ملغ",
      slug: "brufen-400mg",
      brand: "Abbott",
      brandAr: "أبوت",
      description: "Anti-inflammatory pain reliever for moderate to severe pain",
      descriptionAr: "مسكن مضاد للالتهابات للألم المتوسط إلى الشديد",
      price: 18.0,
      stock: 120,
      sku: "BRU-400-001",
      barCode: "6281007002345",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Ibuprofen 400mg",
      activeIngredientAr: "ايبوبروفين 400 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a cool, dry place",
      storageNotesAr: "يحفظ في مكان بارد وجاف",
      warnings: "Not suitable for pregnant women",
      warningsAr: "غير مناسب للحوامل",
      categoryId: categories[0].id,
      rating: 4.5,
      reviewsCount: 189,
      images: ["/brufen-ibuprofen-tablets.jpg"],
    },
    {
      name: "Voltaren Gel",
      nameAr: "فولتارين جل",
      slug: "voltaren-gel",
      brand: "Novartis",
      brandAr: "نوفارتس",
      description: "Topical gel for joint and muscle pain relief",
      descriptionAr: "جل موضعي لتخفيف آلام المفاصل والعضلات",
      price: 35.0,
      stock: 80,
      sku: "VOL-GEL-001",
      barCode: "6281007003456",
      dosageForm: "Gel",
      dosageFormAr: "جل",
      activeIngredient: "Diclofenac Sodium 1%",
      activeIngredientAr: "ديكلوفيناك صوديوم 1%",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "For external use only",
      warningsAr: "للاستخدام الخارجي فقط",
      categoryId: categories[0].id,
      rating: 4.8,
      reviewsCount: 312,
      images: ["/voltaren-gel-tube.jpg"],
    },
    {
      name: "Aspirin 100mg",
      nameAr: "أسبرين 100 ملغ",
      slug: "aspirin-100mg",
      brand: "Bayer",
      brandAr: "باير",
      description: "Low-dose aspirin for heart health and pain relief",
      descriptionAr: "أسبرين بجرعة منخفضة لصحة القلب وتسكين الألم",
      price: 8.5,
      stock: 200,
      sku: "ASP-100-001",
      barCode: "6281007004567",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Acetylsalicylic Acid 100mg",
      activeIngredientAr: "حمض أسيتيل الساليسيليك 100 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Keep in original container",
      storageNotesAr: "يحفظ في العبوة الأصلية",
      warnings: "Consult doctor if on blood thinners",
      warningsAr: "استشر الطبيب إذا كنت تتناول مميعات الدم",
      categoryId: categories[0].id,
      rating: 4.6,
      reviewsCount: 156,
      images: ["/aspirin-tablets-box.jpg"],
    },

    // Vitamins & Supplements
    {
      name: "Centrum Multivitamin",
      nameAr: "سنتروم مالتي فيتامين",
      slug: "centrum-multivitamin",
      brand: "Pfizer",
      brandAr: "فايزر",
      description: "Complete daily multivitamin with essential nutrients",
      descriptionAr: "فيتامينات متعددة يومية كاملة مع العناصر الغذائية الأساسية",
      price: 45.0,
      stock: 95,
      sku: "CEN-MUL-001",
      barCode: "6281007005678",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Multivitamins & Minerals",
      activeIngredientAr: "فيتامينات ومعادن متعددة",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a dry place away from sunlight",
      storageNotesAr: "يحفظ في مكان جاف بعيداً عن أشعة الشمس",
      categoryId: categories[1].id,
      rating: 4.7,
      reviewsCount: 421,
      images: ["/centrum-multivitamin-bottle.jpg"],
    },
    {
      name: "Vitamin D3 5000 IU",
      nameAr: "فيتامين د3 5000 وحدة",
      slug: "vitamin-d3-5000",
      brand: "Nature Made",
      brandAr: "نيتشر ميد",
      description: "High-potency vitamin D for bone and immune health",
      descriptionAr: "فيتامين د عالي الفعالية لصحة العظام والمناعة",
      price: 28.0,
      stock: 110,
      sku: "VIT-D3-001",
      barCode: "6281007006789",
      dosageForm: "Softgels",
      dosageFormAr: "كبسولات جيلاتينية",
      activeIngredient: "Cholecalciferol 5000 IU",
      activeIngredientAr: "كوليكالسيفيرول 5000 وحدة دولية",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      categoryId: categories[1].id,
      rating: 4.9,
      reviewsCount: 567,
      images: ["/vitamin-d3-softgels.jpg"],
    },
    {
      name: "Omega-3 Fish Oil",
      nameAr: "أوميغا 3 زيت السمك",
      slug: "omega-3-fish-oil",
      brand: "Nordic Naturals",
      brandAr: "نورديك ناتشورالز",
      description: "Premium omega-3 for heart and brain health",
      descriptionAr: "أوميغا 3 ممتاز لصحة القلب والدماغ",
      price: 52.0,
      stock: 75,
      sku: "OME-3-001",
      barCode: "6281007007890",
      dosageForm: "Softgels",
      dosageFormAr: "كبسولات جيلاتينية",
      activeIngredient: "EPA 360mg + DHA 240mg",
      activeIngredientAr: "إي بي إيه 360 ملغ + دي إتش إيه 240 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Refrigerate after opening",
      storageNotesAr: "يحفظ في الثلاجة بعد الفتح",
      categoryId: categories[1].id,
      rating: 4.8,
      reviewsCount: 389,
      images: ["/omega-3-capsules.png"],
    },
    {
      name: "Calcium + Vitamin D",
      nameAr: "كالسيوم + فيتامين د",
      slug: "calcium-vitamin-d",
      brand: "Caltrate",
      brandAr: "كالتريت",
      description: "Bone health support with calcium and vitamin D",
      descriptionAr: "دعم صحة العظام بالكالسيوم وفيتامين د",
      price: 32.0,
      stock: 130,
      sku: "CAL-VD-001",
      barCode: "6281007008901",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Calcium 600mg + Vitamin D3 400 IU",
      activeIngredientAr: "كالسيوم 600 ملغ + فيتامين د3 400 وحدة",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a cool, dry place",
      storageNotesAr: "يحفظ في مكان بارد وجاف",
      categoryId: categories[1].id,
      rating: 4.6,
      reviewsCount: 278,
      images: ["/calcium-vitamin-d-tablets.jpg"],
    },

    // Cold & Flu
    {
      name: "Panadol Cold & Flu",
      nameAr: "بانادول كولد اند فلو",
      slug: "panadol-cold-flu",
      brand: "GSK",
      brandAr: "جي إس كي",
      description: "Relief from cold and flu symptoms",
      descriptionAr: "تخفيف أعراض البرد والإنفلونزا",
      price: 15.0,
      stock: 140,
      sku: "PAN-CF-001",
      barCode: "6281007009012",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Paracetamol + Pseudoephedrine + Chlorpheniramine",
      activeIngredientAr: "باراسيتامول + سودوإيفيدرين + كلورفينيرامين",
      isRX: false,
      isOTC: true,
      storageNotes: "Store below 25°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 25 درجة",
      warnings: "May cause drowsiness",
      warningsAr: "قد يسبب النعاس",
      categoryId: categories[2].id,
      rating: 4.5,
      reviewsCount: 298,
      images: ["/panadol-cold-flu-box.jpg"],
    },
    {
      name: "Strepsils Honey & Lemon",
      nameAr: "ستربسلز عسل وليمون",
      slug: "strepsils-honey-lemon",
      brand: "Reckitt",
      brandAr: "ريكيت",
      description: "Soothing lozenges for sore throat relief",
      descriptionAr: "أقراص مهدئة لتخفيف التهاب الحلق",
      price: 9.5,
      stock: 180,
      sku: "STR-HL-001",
      barCode: "6281007010123",
      dosageForm: "Lozenges",
      dosageFormAr: "أقراص استحلاب",
      activeIngredient: "Dichlorobenzyl alcohol + Amylmetacresol",
      activeIngredientAr: "ديكلوروبنزيل الكحول + أميلميتاكريسول",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in original packaging",
      storageNotesAr: "يحفظ في العبوة الأصلية",
      categoryId: categories[2].id,
      rating: 4.7,
      reviewsCount: 445,
      images: ["/strepsils-lozenges-pack.jpg"],
    },
    {
      name: "Vicks VapoRub",
      nameAr: "فيكس فابوراب",
      slug: "vicks-vaporub",
      brand: "Procter & Gamble",
      brandAr: "بروكتر آند جامبل",
      description: "Topical ointment for cough and congestion relief",
      descriptionAr: "مرهم موضعي لتخفيف السعال والاحتقان",
      price: 22.0,
      stock: 100,
      sku: "VIC-VAP-001",
      barCode: "6281007011234",
      dosageForm: "Ointment",
      dosageFormAr: "مرهم",
      activeIngredient: "Camphor + Menthol + Eucalyptus Oil",
      activeIngredientAr: "كافور + منثول + زيت الكافور",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "For external use only, not for children under 2",
      warningsAr: "للاستخدام الخارجي فقط، غير مناسب للأطفال دون السنتين",
      categoryId: categories[2].id,
      rating: 4.8,
      reviewsCount: 523,
      images: ["/vicks-vaporub-jar.jpg"],
    },
    {
      name: "Clarinase",
      nameAr: "كلارينيز",
      slug: "clarinase",
      brand: "Bayer",
      brandAr: "باير",
      description: "Antihistamine for allergy and cold symptoms",
      descriptionAr: "مضاد للهستامين لأعراض الحساسية والبرد",
      price: 24.0,
      stock: 90,
      sku: "CLA-001",
      barCode: "6281007012345",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Loratadine + Pseudoephedrine",
      activeIngredientAr: "لوراتادين + سودوإيفيدرين",
      isRX: false,
      isOTC: true,
      storageNotes: "Store below 30°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 30 درجة",
      categoryId: categories[2].id,
      rating: 4.6,
      reviewsCount: 267,
      images: ["/clarinase-tablets.jpg"],
    },

    // Digestive Health
    {
      name: "Gaviscon Liquid",
      nameAr: "جافيسكون سائل",
      slug: "gaviscon-liquid",
      brand: "Reckitt",
      brandAr: "ريكيت",
      description: "Fast relief from heartburn and indigestion",
      descriptionAr: "تخفيف سريع من حرقة المعدة وعسر الهضم",
      price: 28.0,
      stock: 85,
      sku: "GAV-LIQ-001",
      barCode: "6281007013456",
      dosageForm: "Oral Suspension",
      dosageFormAr: "معلق فموي",
      activeIngredient: "Sodium Alginate + Sodium Bicarbonate",
      activeIngredientAr: "ألجينات الصوديوم + بيكربونات الصوديوم",
      isRX: false,
      isOTC: true,
      storageNotes: "Do not refrigerate",
      storageNotesAr: "لا يحفظ في الثلاجة",
      categoryId: categories[3].id,
      rating: 4.7,
      reviewsCount: 334,
      images: ["/gaviscon-liquid-bottle.jpg"],
    },
    {
      name: "Imodium",
      nameAr: "إيموديوم",
      slug: "imodium",
      brand: "Johnson & Johnson",
      brandAr: "جونسون آند جونسون",
      description: "Fast-acting relief from diarrhea",
      descriptionAr: "تخفيف سريع المفعول من الإسهال",
      price: 16.5,
      stock: 120,
      sku: "IMO-001",
      barCode: "6281007014567",
      dosageForm: "Capsules",
      dosageFormAr: "كبسولات",
      activeIngredient: "Loperamide HCl 2mg",
      activeIngredientAr: "لوبيراميد هيدروكلوريد 2 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "Do not use for more than 2 days without consulting doctor",
      warningsAr: "لا تستخدم لأكثر من يومين دون استشارة الطبيب",
      categoryId: categories[3].id,
      rating: 4.5,
      reviewsCount: 189,
      images: ["/imodium-capsules.jpg"],
    },
    {
      name: "Dulcolax",
      nameAr: "دولكولاكس",
      slug: "dulcolax",
      brand: "Sanofi",
      brandAr: "سانوفي",
      description: "Gentle relief from constipation",
      descriptionAr: "تخفيف لطيف من الإمساك",
      price: 14.0,
      stock: 105,
      sku: "DUL-001",
      barCode: "6281007015678",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Bisacodyl 5mg",
      activeIngredientAr: "بيساكوديل 5 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Store below 25°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 25 درجة",
      categoryId: categories[3].id,
      rating: 4.4,
      reviewsCount: 223,
      images: ["/dulcolax-tablets.jpg"],
    },
    {
      name: "Buscopan",
      nameAr: "بسكوبان",
      slug: "buscopan",
      brand: "Sanofi",
      brandAr: "سانوفي",
      description: "Relief from abdominal cramps and pain",
      descriptionAr: "تخفيف من تقلصات وآلام البطن",
      price: 19.0,
      stock: 95,
      sku: "BUS-001",
      barCode: "6281007016789",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Hyoscine Butylbromide 10mg",
      activeIngredientAr: "هيوسين بوتيل بروميد 10 ملغ",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a dry place",
      storageNotesAr: "يحفظ في مكان جاف",
      categoryId: categories[3].id,
      rating: 4.6,
      reviewsCount: 312,
      images: ["/buscopan-tablets.jpg"],
    },

    // Skin Care
    {
      name: "Cetaphil Gentle Cleanser",
      nameAr: "سيتافيل منظف لطيف",
      slug: "cetaphil-gentle-cleanser",
      brand: "Galderma",
      brandAr: "جالديرما",
      description: "Gentle cleanser for all skin types",
      descriptionAr: "منظف لطيف لجميع أنواع البشرة",
      price: 42.0,
      stock: 70,
      sku: "CET-CLE-001",
      barCode: "6281007017890",
      dosageForm: "Liquid",
      dosageFormAr: "سائل",
      activeIngredient: "Mild surfactants",
      activeIngredientAr: "مواد فعالة سطحية خفيفة",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      categoryId: categories[4].id,
      rating: 4.8,
      reviewsCount: 678,
      images: ["/cetaphil-cleanser-bottle.jpg"],
    },
    {
      name: "La Roche-Posay Sunscreen SPF 50",
      nameAr: "لاروش بوزيه واقي شمس 50",
      slug: "laroche-posay-sunscreen-spf50",
      brand: "La Roche-Posay",
      brandAr: "لاروش بوزيه",
      description: "High protection sunscreen for sensitive skin",
      descriptionAr: "واقي شمس عالي الحماية للبشرة الحساسة",
      price: 68.0,
      stock: 55,
      sku: "LRP-SUN-001",
      barCode: "6281007018901",
      dosageForm: "Cream",
      dosageFormAr: "كريم",
      activeIngredient: "Mexoryl XL + Titanium Dioxide",
      activeIngredientAr: "ميكسوريل إكس إل + ثاني أكسيد التيتانيوم",
      isRX: false,
      isOTC: true,
      storageNotes: "Store away from direct sunlight",
      storageNotesAr: "يحفظ بعيداً عن أشعة الشمس المباشرة",
      categoryId: categories[4].id,
      rating: 4.9,
      reviewsCount: 892,
      images: ["/sunscreen-spf50-tube.jpg"],
    },
    {
      name: "Bioderma Sensibio H2O",
      nameAr: "بيوديرما سينسيبيو اتش تو او",
      slug: "bioderma-sensibio-h2o",
      brand: "Bioderma",
      brandAr: "بيوديرما",
      description: "Micellar water for sensitive skin cleansing",
      descriptionAr: "ماء ميسيلار لتنظيف البشرة الحساسة",
      price: 55.0,
      stock: 65,
      sku: "BIO-SEN-001",
      barCode: "6281007019012",
      dosageForm: "Solution",
      dosageFormAr: "محلول",
      activeIngredient: "Micellar technology",
      activeIngredientAr: "تقنية ميسيلار",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      categoryId: categories[4].id,
      rating: 4.7,
      reviewsCount: 534,
      images: ["/bioderma-micellar-water.jpg"],
    },
    {
      name: "Eucerin Aquaphor",
      nameAr: "يوسيرين أكوافور",
      slug: "eucerin-aquaphor",
      brand: "Eucerin",
      brandAr: "يوسيرين",
      description: "Healing ointment for dry and cracked skin",
      descriptionAr: "مرهم علاجي للبشرة الجافة والمتشققة",
      price: 38.0,
      stock: 80,
      sku: "EUC-AQU-001",
      barCode: "6281007020123",
      dosageForm: "Ointment",
      dosageFormAr: "مرهم",
      activeIngredient: "Petrolatum + Glycerin",
      activeIngredientAr: "فازلين + جليسرين",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a cool place",
      storageNotesAr: "يحفظ في مكان بارد",
      categoryId: categories[4].id,
      rating: 4.8,
      reviewsCount: 445,
      images: ["/eucerin-aquaphor-ointment.jpg"],
    },

    // Heart & Blood Pressure
    {
      name: "Concor 5mg",
      nameAr: "كونكور 5 ملغ",
      slug: "concor-5mg",
      brand: "Merck",
      brandAr: "ميرك",
      description: "Beta-blocker for high blood pressure and heart conditions",
      descriptionAr: "حاصر بيتا لارتفاع ضغط الدم وأمراض القلب",
      price: 45.0,
      stock: 60,
      sku: "CON-5-001",
      barCode: "6281007021234",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Bisoprolol Fumarate 5mg",
      activeIngredientAr: "بيسوبرولول فومارات 5 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store below 25°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 25 درجة",
      warnings: "Prescription required. Do not stop suddenly.",
      warningsAr: "يتطلب وصفة طبية. لا توقف الدواء فجأة.",
      categoryId: categories[5].id,
      rating: 4.6,
      reviewsCount: 234,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Norvasc 10mg",
      nameAr: "نورفاسك 10 ملغ",
      slug: "norvasc-10mg",
      brand: "Pfizer",
      brandAr: "فايزر",
      description: "Calcium channel blocker for hypertension",
      descriptionAr: "حاصر قنوات الكالسيوم لارتفاع ضغط الدم",
      price: 52.0,
      stock: 50,
      sku: "NOR-10-001",
      barCode: "6281007022345",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Amlodipine Besylate 10mg",
      activeIngredientAr: "أملوديبين بيسيلات 10 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "Prescription required",
      warningsAr: "يتطلب وصفة طبية",
      categoryId: categories[5].id,
      rating: 4.7,
      reviewsCount: 189,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Plavix 75mg",
      nameAr: "بلافيكس 75 ملغ",
      slug: "plavix-75mg",
      brand: "Sanofi",
      brandAr: "سانوفي",
      description: "Antiplatelet medication to prevent blood clots",
      descriptionAr: "دواء مضاد للصفيحات لمنع تجلط الدم",
      price: 85.0,
      stock: 40,
      sku: "PLA-75-001",
      barCode: "6281007023456",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Clopidogrel 75mg",
      activeIngredientAr: "كلوبيدوجريل 75 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store in original container",
      storageNotesAr: "يحفظ في العبوة الأصلية",
      warnings: "Prescription required. May increase bleeding risk.",
      warningsAr: "يتطلب وصفة طبية. قد يزيد من خطر النزيف.",
      categoryId: categories[5].id,
      rating: 4.5,
      reviewsCount: 156,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Lipitor 20mg",
      nameAr: "ليبيتور 20 ملغ",
      slug: "lipitor-20mg",
      brand: "Pfizer",
      brandAr: "فايزر",
      description: "Statin for cholesterol management",
      descriptionAr: "ستاتين لإدارة الكوليسترول",
      price: 62.0,
      stock: 55,
      sku: "LIP-20-001",
      barCode: "6281007024567",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Atorvastatin 20mg",
      activeIngredientAr: "أتورفاستاتين 20 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "Prescription required",
      warningsAr: "يتطلب وصفة طبية",
      categoryId: categories[5].id,
      rating: 4.6,
      reviewsCount: 278,
      images: ["/placeholder.svg?height=400&width=400"],
    },

    // Diabetes Care
    {
      name: "Glucophage 500mg",
      nameAr: "جلوكوفاج 500 ملغ",
      slug: "glucophage-500mg",
      brand: "Merck",
      brandAr: "ميرك",
      description: "Metformin for type 2 diabetes management",
      descriptionAr: "ميتفورمين لإدارة السكري من النوع الثاني",
      price: 28.0,
      stock: 100,
      sku: "GLU-500-001",
      barCode: "6281007025678",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Metformin HCl 500mg",
      activeIngredientAr: "ميتفورمين هيدروكلوريد 500 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store below 25°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 25 درجة",
      warnings: "Prescription required. Take with meals.",
      warningsAr: "يتطلب وصفة طبية. يؤخذ مع الوجبات.",
      categoryId: categories[6].id,
      rating: 4.5,
      reviewsCount: 412,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Lantus SoloStar",
      nameAr: "لانتوس سولوستار",
      slug: "lantus-solostar",
      brand: "Sanofi",
      brandAr: "سانوفي",
      description: "Long-acting insulin for diabetes",
      descriptionAr: "أنسولين طويل المفعول لمرضى السكري",
      price: 145.0,
      stock: 30,
      sku: "LAN-SOL-001",
      barCode: "6281007026789",
      dosageForm: "Injection",
      dosageFormAr: "حقن",
      activeIngredient: "Insulin Glargine 100 units/mL",
      activeIngredientAr: "أنسولين جلارجين 100 وحدة/مل",
      isRX: true,
      isOTC: false,
      storageNotes: "Refrigerate. Do not freeze.",
      storageNotesAr: "يحفظ في الثلاجة. لا يجمد.",
      warnings: "Prescription required. Proper injection technique required.",
      warningsAr: "يتطلب وصفة طبية. يتطلب تقنية حقن صحيحة.",
      categoryId: categories[6].id,
      rating: 4.8,
      reviewsCount: 567,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Accu-Chek Test Strips",
      nameAr: "أكيو تشيك شرائط فحص",
      slug: "accuchek-test-strips",
      brand: "Roche",
      brandAr: "روش",
      description: "Blood glucose test strips for diabetes monitoring",
      descriptionAr: "شرائط فحص جلوكوز الدم لمراقبة السكري",
      price: 95.0,
      stock: 75,
      sku: "ACC-STR-001",
      barCode: "6281007027890",
      dosageForm: "Test Strips",
      dosageFormAr: "شرائط فحص",
      activeIngredient: "Glucose oxidase enzyme",
      activeIngredientAr: "إنزيم أكسيداز الجلوكوز",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in original container, away from moisture",
      storageNotesAr: "يحفظ في العبوة الأصلية، بعيداً عن الرطوبة",
      categoryId: categories[6].id,
      rating: 4.7,
      reviewsCount: 389,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Januvia 100mg",
      nameAr: "جانوفيا 100 ملغ",
      slug: "januvia-100mg",
      brand: "MSD",
      brandAr: "إم إس دي",
      description: "DPP-4 inhibitor for type 2 diabetes",
      descriptionAr: "مثبط دي بي بي-4 لمرض السكري من النوع الثاني",
      price: 125.0,
      stock: 45,
      sku: "JAN-100-001",
      barCode: "6281007028901",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Sitagliptin 100mg",
      activeIngredientAr: "سيتاجليبتين 100 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "Prescription required",
      warningsAr: "يتطلب وصفة طبية",
      categoryId: categories[6].id,
      rating: 4.6,
      reviewsCount: 223,
      images: ["/placeholder.svg?height=400&width=400"],
    },

    // Antibiotics
    {
      name: "Augmentin 1g",
      nameAr: "أوجمنتين 1 جرام",
      slug: "augmentin-1g",
      brand: "GSK",
      brandAr: "جي إس كي",
      description: "Broad-spectrum antibiotic for bacterial infections",
      descriptionAr: "مضاد حيوي واسع الطيف للعدوى البكتيرية",
      price: 48.0,
      stock: 70,
      sku: "AUG-1G-001",
      barCode: "6281007029012",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Amoxicillin 875mg + Clavulanic Acid 125mg",
      activeIngredientAr: "أموكسيسيلين 875 ملغ + حمض كلافولانيك 125 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store in a cool, dry place",
      storageNotesAr: "يحفظ في مكان بارد وجاف",
      warnings: "Prescription required. Complete full course.",
      warningsAr: "يتطلب وصفة طبية. أكمل الدورة كاملة.",
      categoryId: categories[7].id,
      rating: 4.6,
      reviewsCount: 345,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Zithromax 500mg",
      nameAr: "زيثروماكس 500 ملغ",
      slug: "zithromax-500mg",
      brand: "Pfizer",
      brandAr: "فايزر",
      description: "Azithromycin antibiotic for respiratory infections",
      descriptionAr: "مضاد حيوي أزيثروميسين للعدوى التنفسية",
      price: 55.0,
      stock: 60,
      sku: "ZIT-500-001",
      barCode: "6281007030123",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Azithromycin 500mg",
      activeIngredientAr: "أزيثروميسين 500 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store below 30°C",
      storageNotesAr: "يحفظ في درجة حرارة أقل من 30 درجة",
      warnings: "Prescription required",
      warningsAr: "يتطلب وصفة طبية",
      categoryId: categories[7].id,
      rating: 4.7,
      reviewsCount: 289,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Cipro 500mg",
      nameAr: "سيبرو 500 ملغ",
      slug: "cipro-500mg",
      brand: "Bayer",
      brandAr: "باير",
      description: "Fluoroquinolone antibiotic for various infections",
      descriptionAr: "مضاد حيوي فلوروكينولون لعدوى متنوعة",
      price: 42.0,
      stock: 55,
      sku: "CIP-500-001",
      barCode: "6281007031234",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Ciprofloxacin 500mg",
      activeIngredientAr: "سيبروفلوكساسين 500 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "Prescription required. Avoid dairy products.",
      warningsAr: "يتطلب وصفة طبية. تجنب منتجات الألبان.",
      categoryId: categories[7].id,
      rating: 4.5,
      reviewsCount: 267,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Flagyl 500mg",
      nameAr: "فلاجيل 500 ملغ",
      slug: "flagyl-500mg",
      brand: "Sanofi",
      brandAr: "سانوفي",
      description: "Antibiotic for anaerobic bacterial and protozoal infections",
      descriptionAr: "مضاد حيوي للعدوى البكتيرية اللاهوائية والأوالي",
      price: 32.0,
      stock: 80,
      sku: "FLA-500-001",
      barCode: "6281007032345",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Metronidazole 500mg",
      activeIngredientAr: "ميترونيدازول 500 ملغ",
      isRX: true,
      isOTC: false,
      storageNotes: "Store in original container",
      storageNotesAr: "يحفظ في العبوة الأصلية",
      warnings: "Prescription required. Avoid alcohol.",
      warningsAr: "يتطلب وصفة طبية. تجنب الكحول.",
      categoryId: categories[7].id,
      rating: 4.4,
      reviewsCount: 198,
      images: ["/placeholder.svg?height=400&width=400"],
    },

    // Baby & Mother Care
    {
      name: "Aptamil Baby Formula",
      nameAr: "أبتاميل حليب أطفال",
      slug: "aptamil-baby-formula",
      brand: "Nutricia",
      brandAr: "نوتريشيا",
      description: "Premium infant formula for babies 0-6 months",
      descriptionAr: "حليب أطفال ممتاز للرضع من 0-6 أشهر",
      price: 85.0,
      stock: 90,
      sku: "APT-FOR-001",
      barCode: "6281007033456",
      dosageForm: "Powder",
      dosageFormAr: "بودرة",
      activeIngredient: "Milk proteins, vitamins, minerals",
      activeIngredientAr: "بروتينات الحليب، فيتامينات، معادن",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a cool, dry place. Use within 4 weeks of opening.",
      storageNotesAr: "يحفظ في مكان بارد وجاف. يستخدم خلال 4 أسابيع من الفتح.",
      categoryId: categories[8].id,
      rating: 4.8,
      reviewsCount: 756,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Pampers Baby Wipes",
      nameAr: "بامبرز مناديل أطفال",
      slug: "pampers-baby-wipes",
      brand: "Procter & Gamble",
      brandAr: "بروكتر آند جامبل",
      description: "Gentle baby wipes for sensitive skin",
      descriptionAr: "مناديل أطفال لطيفة للبشرة الحساسة",
      price: 18.0,
      stock: 150,
      sku: "PAM-WIP-001",
      barCode: "6281007034567",
      dosageForm: "Wipes",
      dosageFormAr: "مناديل",
      activeIngredient: "Purified water, mild cleansers",
      activeIngredientAr: "ماء نقي، منظفات خفيفة",
      isRX: false,
      isOTC: true,
      storageNotes: "Keep sealed to prevent drying",
      storageNotesAr: "يحفظ مغلقاً لمنع الجفاف",
      categoryId: categories[8].id,
      rating: 4.7,
      reviewsCount: 623,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Prenatal Vitamins",
      nameAr: "فيتامينات ما قبل الولادة",
      slug: "prenatal-vitamins",
      brand: "Nature Made",
      brandAr: "نيتشر ميد",
      description: "Complete prenatal vitamin for pregnant and nursing mothers",
      descriptionAr: "فيتامينات كاملة قبل الولادة للحوامل والمرضعات",
      price: 58.0,
      stock: 70,
      sku: "PRE-VIT-001",
      barCode: "6281007035678",
      dosageForm: "Tablets",
      dosageFormAr: "أقراص",
      activeIngredient: "Folic Acid, Iron, Calcium, DHA",
      activeIngredientAr: "حمض الفوليك، حديد، كالسيوم، دي إتش إيه",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      categoryId: categories[8].id,
      rating: 4.9,
      reviewsCount: 834,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Gripe Water",
      nameAr: "ماء غريب",
      slug: "gripe-water",
      brand: "Woodwards",
      brandAr: "وودواردز",
      description: "Natural relief for infant colic and gas",
      descriptionAr: "تخفيف طبيعي لمغص الرضع والغازات",
      price: 22.0,
      stock: 100,
      sku: "GRI-WAT-001",
      barCode: "6281007036789",
      dosageForm: "Liquid",
      dosageFormAr: "سائل",
      activeIngredient: "Dill seed oil, Sodium bicarbonate",
      activeIngredientAr: "زيت بذور الشبت، بيكربونات الصوديوم",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a cool place",
      storageNotesAr: "يحفظ في مكان بارد",
      categoryId: categories[8].id,
      rating: 4.6,
      reviewsCount: 445,
      images: ["/placeholder.svg?height=400&width=400"],
    },

    // First Aid
    {
      name: "Band-Aid Adhesive Bandages",
      nameAr: "باند ايد ضمادات لاصقة",
      slug: "bandaid-adhesive-bandages",
      brand: "Johnson & Johnson",
      brandAr: "جونسون آند جونسون",
      description: "Sterile adhesive bandages for minor cuts and wounds",
      descriptionAr: "ضمادات لاصقة معقمة للجروح والخدوش الصغيرة",
      price: 12.0,
      stock: 180,
      sku: "BAN-AID-001",
      barCode: "6281007037890",
      dosageForm: "Bandages",
      dosageFormAr: "ضمادات",
      activeIngredient: "Sterile pad",
      activeIngredientAr: "ضمادة معقمة",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in a dry place",
      storageNotesAr: "يحفظ في مكان جاف",
      categoryId: categories[9].id,
      rating: 4.5,
      reviewsCount: 234,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Betadine Antiseptic Solution",
      nameAr: "بيتادين محلول مطهر",
      slug: "betadine-antiseptic",
      brand: "Mundipharma",
      brandAr: "مونديفارما",
      description: "Antiseptic solution for wound cleaning and disinfection",
      descriptionAr: "محلول مطهر لتنظيف وتعقيم الجروح",
      price: 24.0,
      stock: 95,
      sku: "BET-ANT-001",
      barCode: "6281007038901",
      dosageForm: "Solution",
      dosageFormAr: "محلول",
      activeIngredient: "Povidone-Iodine 10%",
      activeIngredientAr: "بوفيدون يود 10%",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature, away from light",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة، بعيداً عن الضوء",
      warnings: "For external use only",
      warningsAr: "للاستخدام الخارجي فقط",
      categoryId: categories[9].id,
      rating: 4.8,
      reviewsCount: 512,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Hydrogen Peroxide 3%",
      nameAr: "بيروكسيد الهيدروجين 3%",
      slug: "hydrogen-peroxide-3",
      brand: "Generic",
      brandAr: "عام",
      description: "Antiseptic for minor cuts and wound cleaning",
      descriptionAr: "مطهر للجروح الصغيرة وتنظيف الجروح",
      price: 8.0,
      stock: 140,
      sku: "HYD-PER-001",
      barCode: "6281007039012",
      dosageForm: "Solution",
      dosageFormAr: "محلول",
      activeIngredient: "Hydrogen Peroxide 3%",
      activeIngredientAr: "بيروكسيد الهيدروجين 3%",
      isRX: false,
      isOTC: true,
      storageNotes: "Store in original brown bottle, away from light",
      storageNotesAr: "يحفظ في الزجاجة البنية الأصلية، بعيداً عن الضوء",
      warnings: "For external use only",
      warningsAr: "للاستخدام الخارجي فقط",
      categoryId: categories[9].id,
      rating: 4.4,
      reviewsCount: 178,
      images: ["/placeholder.svg?height=400&width=400"],
    },
    {
      name: "Burn Gel",
      nameAr: "جل الحروق",
      slug: "burn-gel",
      brand: "Burnshield",
      brandAr: "بيرنشيلد",
      description: "Cooling gel for minor burns and scalds",
      descriptionAr: "جل مبرد للحروق والسمط الطفيف",
      price: 28.0,
      stock: 65,
      sku: "BUR-GEL-001",
      barCode: "6281007040123",
      dosageForm: "Gel",
      dosageFormAr: "جل",
      activeIngredient: "Tea tree oil, Aloe vera",
      activeIngredientAr: "زيت شجرة الشاي، الصبار",
      isRX: false,
      isOTC: true,
      storageNotes: "Store at room temperature",
      storageNotesAr: "يحفظ في درجة حرارة الغرفة",
      warnings: "For minor burns only. Seek medical help for severe burns.",
      warningsAr: "للحروق الطفيفة فقط. اطلب المساعدة الطبية للحروق الشديدة.",
      categoryId: categories[9].id,
      rating: 4.7,
      reviewsCount: 289,
      images: ["/placeholder.svg?height=400&width=400"],
    },
  ]

  for (const productData of products) {
    await prisma.product.create({ data: productData })
  }

  console.log(`✅ Created ${products.length} products`)

  // Create tags
  const tags = await Promise.all([
    prisma.tag.create({
      data: { name: "Bestseller", nameAr: "الأكثر مبيعاً", slug: "bestseller" },
    }),
    prisma.tag.create({
      data: { name: "New Arrival", nameAr: "وصل حديثاً", slug: "new-arrival" },
    }),
    prisma.tag.create({
      data: { name: "On Sale", nameAr: "عرض خاص", slug: "on-sale" },
    }),
  ])

  console.log(`✅ Created ${tags.length} tags`)

  console.log("✅ Database seeded successfully!")
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
